<?xml version="1.0" encoding="utf-8" ?>
<Project>
    <PropertyGroup>
		<GamePath>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag</GamePath>
		<GameAssemblyPath>$(GamePath)\Gorilla Tag_Data\Managed</GameAssemblyPath>
        <BepInExAssemblyPath>$(GamePath)\BepInEx\core</BepInExAssemblyPath>
        <PluginsPath>$(GamePath)\BepInEx\plugins\OculusReportMenu</PluginsPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(CI)'=='true'">
        <GamePath>.\Libs</GamePath>
		<GameAssemblyPath>.\Libs</GameAssemblyPath>
        <BepInExAssemblyPath>.\Libs</BepInExAssemblyPath>
    </PropertyGroup>
</Project>
